---
extends:
  - tribou

plugins:
  - flowtype-errors

rules:
  flowtype-errors/show-errors: 2
  quote-props:
    - error
    - as-needed
    - numbers: true

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true
