---
extends:
  - plugin:tribou/recommended

plugins:
  - tribou

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: false
  import/resolver: webpack
  react/prefer-stateless-function:
    - ignorePureComponents: true
