---
extends:
  - tribou
  - plugin:flowtype/recommended

plugins:
  - flowtype-errors

rules:
  flowtype-errors/show-errors: 2

  flowtype/require-valid-file-annotation:
    - error
    - always

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: false
