---
extends:
  - tribou
  - plugin:flowtype/recommended

rules:
  flowtype/require-valid-file-annotation:
    - error
    - always

  no-duplicate-imports: 0

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: false

env:
  jest: true
